# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    working-directory: ~/bands-api
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      SBT_VERSION: 1.1.1
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: echo "Build"

  unit-tests:
    working-directory: ~/bands-api
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: echo "Unit tests"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
